apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-ha
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wordpress

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi