version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: